baseURL: https://website-valerio-hetlinger.netlify.app/
languageCode: en-us
title: Website Valerio Hetlinger
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    #subtitle: |-
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Valerio and I am part of the MFA2022 cohort at London Business School
  blog: {}
  contact:
    address:
      - city: London, W23NF
        country: United Kingdom
        street: Oxford Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: vhetlinger.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +43 699 18415087
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Valerio Hetlinger
    enable: yes
    quicklinks:
     # - alt: HTML5 UP
      #  text: 'Design: '
       # url: https://www.html5up.net
    social:
      #- icon: fa-twitter
       # label: Twitter
        #url: https://www.twitter.com
      #- icon: fa-facebook
        #label: Facebook
        #url: https://www.facebook.com
      #- icon: fa-instagram
       # label: Instagram
       # url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/valeriohetlinger
  image: ''
  name: Valerio Hetlinger
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
     # - name: Elements
      #  url: elements.html
    menu: Menu
    #subtitle: By HTML5 Up
    #title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: A short biography
        title: About me
        url: blogs/me
      - image: CV.jpg
        subtitle: Feel free to give a look at my current CV
        title: CV
        url: blogs/magna #slug of rmd!
      - image: CV.jpg
        subtitle: kostis output
        title: DJIA Performance
        url: blogs/risk_return
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/me
      #- image: pic05.jpg
        #subtitle: Ipsum Dolor Sit Amet
        #title: Consequat
        #url: blogs/ipsum
      #- image: pic06.jpg
       # subtitle: Feugiat Amet Tempus
        #title: Etiam
        #url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
